steps:
  - name: 'maven:3.6.3-jdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy --quiet
options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you prefer